# Generated by Django 5.0.4 on 2024-04-12 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_360', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='citizen_id',
            field=models.CharField(default=None, help_text='Enter your Citizen ID in the format CZN00001.', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message="Citizen ID must be in the format 'CZN00001' where digits follow 'CZN'.", regex='^CZN\\d{5}$')]),
        ),
    ]
