# Generated by Django 5.0.4 on 2024-04-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_360', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytaxpropertydetail',
            name='verification_id',
            field=models.IntegerField(),
        ),
    ]
