# Generated by Django 5.0.4 on 2024-04-12 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_360', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='citizen_id',
            field=models.CharField(help_text='Enter your Citizen ID in the format CZN00001.', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message="Citizen ID must be in the format 'CZN00001' where digits follow 'CZN'.", regex='^CZN\\d{5}$')]),
        ),
    ]
