# Generated by Django 5.0.4 on 2024-04-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_360', '0003_gis_pincode_ward_peth'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytaxtaxrate',
            name='property_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('non-residential', 'Non-Residential')], default=None, max_length=100),
            preserve_default=False,
        ),
    ]
