# Generated by Django 5.0.4 on 2024-04-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_360', '0004_propertytaxtaxrate_property_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='propertytaxpropertysubtype',
            table='property_tax_property_subtype',
        ),
    ]
