# Generated by Django 5.0.4 on 2024-04-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_360', '0005_alter_propertytaxpropertysubtype_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytaxpropertydetail',
            name='property_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('non-residential', 'Non-Residential'), ('open-plot', 'Open Plot')], max_length=100),
        ),
        migrations.AlterField(
            model_name='propertytaxpropertysubtype',
            name='property_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('non-residential', 'Non-Residential'), ('open-plot', 'Open Plot')], max_length=100),
        ),
        migrations.AlterField(
            model_name='propertytaxpropertytype',
            name='property_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('non-residential', 'Non-Residential'), ('open-plot', 'Open Plot')], max_length=100),
        ),
        migrations.AlterField(
            model_name='propertytaxtaxrate',
            name='property_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('non-residential', 'Non-Residential'), ('open-plot', 'Open Plot')], max_length=100),
        ),
    ]
