# Generated by Django 5.0.4 on 2024-04-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_360', '0005_remove_customuser_citizen_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='government_id',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
