# Generated by Django 5.0.4 on 2024-04-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_360', '0006_alter_propertytaxpropertydetail_property_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertytaxapplicationformhistory',
            name='id',
        ),
        migrations.AddField(
            model_name='propertytaxapplicationformhistory',
            name='application_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
