# Generated by Django 5.0.4 on 2024-04-15 07:32

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_360', '0006_customuser_government_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='aadhar_card_id',
            field=models.CharField(blank=True, default=None, max_length=12, validators=[django.core.validators.RegexValidator(message='Aadhar card number must be 12 digits.', regex='^\\d{12}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pan_card_id',
            field=models.CharField(blank=True, default=None, max_length=10, validators=[django.core.validators.RegexValidator(message="PAN card number must be in the format: 'ABCDE1234F'.", regex='^[A-Z]{5}\\d{4}[A-Z]$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ration_card_id',
            field=models.CharField(blank=True, default=None, max_length=12, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
    ]
