# Generated by Django 5.0.4 on 2024-04-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_360', '0008_alter_propertytaxpropertydetail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytaxpropertyaddress',
            name='pincode',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
