# Generated by Django 5.0.4 on 2024-04-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_360', '0008_alter_customuser_aadhar_card_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(default=None, help_text='Enter your address.', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateField(default=None, help_text='Enter your date of birth.', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='geographical_details',
            field=models.JSONField(default=None, help_text='Enter geographical details as JSON.', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='government_id',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nationality',
            field=models.CharField(default=None, help_text='Enter your nationality.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='occupation',
            field=models.CharField(default=None, help_text='Enter your occupation.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='place_of_birth',
            field=models.CharField(default=None, help_text='Enter your place of birth.', max_length=100, null=True),
        ),
    ]
