# Generated by Django 5.0.4 on 2024-04-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_360', '0009_propertytaxpropertyaddress_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytaxpropertydetail',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertytaxpropertydetail',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9),
            preserve_default=False,
        ),
    ]
