# Generated by Django 5.0.4 on 2024-04-26 06:10

import django.core.validators
import django.db.models.deletion
import portal_360.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_360', '0010_propertytaxpropertydetail_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSComplaintType',
            fields=[
                ('complaint_type_id', models.IntegerField(db_column='complaint_type_id', primary_key=True, serialize=False, verbose_name='Complaint Type ID')),
                ('complaint_type', models.CharField(choices=[(1, 'Property Tax-Computer Section'), (2, 'Property TaxAssessment/Payment'), (3, 'Property Tax-Mobile tower'), (4, 'Property Tax-Solar & Rainwater'), (5, 'Property Tax-TAT (Title Transfer)'), (6, 'Water Supply'), (7, 'Urban Poor Scheme'), (8, 'Building Permission')], db_column='complaint_type', max_length=255)),
            ],
            options={
                'db_table': 'cms_complaint_type',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'department_master',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pan_card_id',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, unique=True, validators=[portal_360.models.pan_card_validator]),
        ),
        migrations.CreateModel(
            name='CMSComplaintSubType',
            fields=[
                ('complaint_sub_type_id', models.IntegerField(db_column='complaint_sub_type_id', primary_key=True, serialize=False, verbose_name='Complaint Sub Type ID')),
                ('complaint_sub_type', models.CharField(choices=[(1, 'Property Tax-Computer Section'), (2, 'Property TaxAssessment/Payment'), (3, 'Property Tax-Mobile tower'), (4, 'Property Tax-Solar & Rainwater'), (5, 'Property Tax-TAT (Title Transfer)'), (6, 'Water Supply'), (7, 'Urban Poor Scheme'), (8, 'Building Permission')], db_column='complaint_sub_type', max_length=255)),
                ('complaint_type_id', models.ForeignKey(db_column='complaint_type_id', on_delete=django.db.models.deletion.CASCADE, to='portal_360.cmscomplainttype')),
            ],
            options={
                'db_table': 'cms_complaint_subtype',
            },
        ),
        migrations.CreateModel(
            name='CMSComplaints',
            fields=[
                ('complaint_id', models.AutoField(db_column='complaint_id', primary_key=True, serialize=False, verbose_name='Complaint ID')),
                ('registration_date', models.DateField(db_column='registration_date')),
                ('expected_completion_date', models.DateField(db_column='expected_completion_date')),
                ('description', models.TextField(db_column='description')),
                ('status', models.CharField(db_column='status', max_length=50)),
                ('completion_date', models.DateField(blank=True, db_column='completion_date', null=True)),
                ('rating', models.IntegerField(blank=True, db_column='rating', null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('feedback', models.TextField(blank=True, db_column='feedback', null=True)),
                ('reopen', models.BooleanField(db_column='reopen', default=False)),
                ('address', models.CharField(db_column='address', max_length=255)),
                ('gis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_360.gis')),
                ('peth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_360.peth')),
                ('pincode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_360.pincode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(db_column='ward_id', on_delete=django.db.models.deletion.CASCADE, to='portal_360.ward')),
                ('complaint_sub_type_id', models.ForeignKey(db_column='complaint_sub_type_id', on_delete=django.db.models.deletion.CASCADE, to='portal_360.cmscomplaintsubtype')),
                ('complaint_type_id', models.ForeignKey(db_column='complaint_type_id', on_delete=django.db.models.deletion.CASCADE, to='portal_360.cmscomplainttype')),
                ('department', models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_360.department')),
            ],
            options={
                'db_table': 'complaints',
            },
        ),
    ]
