# Generated by Django 5.0.4 on 2024-04-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_360', '0010_alter_customuser_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=None, help_text='Please enter your username', max_length=150, unique=True),
        ),
    ]
