# Generated by Django 5.0.4 on 2024-04-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_360', '0011_cmscomplainttype_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmscomplaints',
            name='subject',
            field=models.TextField(db_column='subject', default=None),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='cmscomplaints',
            table='cms_complaints',
        ),
    ]
