# Generated by Django 5.0.4 on 2024-04-28 11:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_360', '0013_alter_cmscomplaintsubtype_complaint_sub_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmscomplaints',
            name='expected_completion_date',
            field=models.DateField(blank=True, db_column='expected_completion_date', null=True),
        ),
        migrations.AlterField(
            model_name='cmscomplaints',
            name='registration_date',
            field=models.DateField(db_column='registration_date', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cmscomplaints',
            name='status',
            field=models.CharField(db_column='status', default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='cmscomplainttype',
            name='complaint_type',
            field=models.CharField(choices=[(1, 'Property Tax-Computer Section'), (2, 'Property TaxAssessment/Payment'), (3, 'Property Tax-Mobile tower'), (4, 'Property Tax-Solar & Rainwater'), (5, 'Property Tax-TAT (Title Transfer)'), (6, 'Water Supply'), (7, 'Urban Poor Scheme'), (8, 'Building Permission'), (9, 'Incorrect Billing'), (10, 'Late Payment Charges'), (11, 'Exemptions Not Applied'), (12, 'Water Quality'), (13, 'Water Supply Disruption'), (14, 'Low Water Pressure'), (15, 'Illegal Settlements'), (16, 'Sanitation Issue'), (17, 'Lack of Infrastructure'), (18, 'Public Land Encroachment'), (19, 'Unauthorized Vendors'), (20, 'Illegal Parking'), (21, 'Delay in Permit Issuance'), (22, 'Illegal Construction'), (23, 'Unapproved Building Materials'), (24, 'Unhygienic Conditions'), (25, 'Hospital Waste Management'), (26, 'Improper Disposal of Medical Waste')], db_column='complaint_type'),
        ),
    ]
