# Generated by Django 5.0.4 on 2024-04-30 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_360', '0016_customuser_age_customuser_disability_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PBCostEstimate',
            fields=[
                ('cost_estimate_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_estimate_range', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pb_cost_estimate_master',
            },
        ),
        migrations.CreateModel(
            name='PBProjectCategory',
            fields=[
                ('project_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_category_name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_360.department')),
            ],
            options={
                'db_table': 'pb_project_category_master',
            },
        ),
        migrations.CreateModel(
            name='PBProjects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('submission_timestamp', models.DateTimeField()),
                ('project_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cost_estimate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocated_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_spent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('priority_level', models.IntegerField()),
                ('requested_deadline', models.DateField()),
                ('estimated_deadline', models.DateField()),
                ('final_implementation_status', models.CharField(choices=[('application_submitted', 'Application Submitted'), ('approved', 'Approved'), ('completed', 'Completed'), ('ongoing', 'Ongoing'), ('rejected', 'Rejected')], max_length=255)),
                ('officer_remarks', models.TextField(blank=True, null=True)),
                ('completion_timestamp', models.DateTimeField(blank=True, null=True)),
                ('citizen_rating', models.IntegerField(blank=True, null=True)),
                ('citizen_feedback', models.TextField(blank=True, null=True)),
                ('tat', models.IntegerField()),
                ('total_votes_received', models.IntegerField()),
                ('assigned_officer', models.CharField(max_length=255)),
                ('assigned_officer_id', models.IntegerField()),
                ('supporting_documents', models.BooleanField(default=False)),
                ('beneficiary', models.CharField(choices=[('citizen', 'Citizen'), ('student', 'Student'), ('slum', 'Low-Income Strata')])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_360.department')),
                ('gis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_360.gis')),
                ('project_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_360.pbprojectcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_360.ward')),
            ],
            options={
                'db_table': 'pb_project_master',
            },
        ),
        migrations.CreateModel(
            name='PBBudget',
            fields=[
                ('budget_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_estimate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocated_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_spent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('assigned_officer', models.CharField(max_length=255)),
                ('assigned_officer_id', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_360.department')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_360.ward')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_360.pbprojects')),
            ],
            options={
                'db_table': 'pb_budget_master',
            },
        ),
        migrations.CreateModel(
            name='PBVoting',
            fields=[
                ('voting_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_category', models.CharField(max_length=255)),
                ('vote_timestamp', models.DateTimeField()),
                ('vote_type', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('neutral', 'Neutral')], max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_360.department')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_360.pbprojects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pb_voting_master',
            },
        ),
    ]
