# Generated by Django 5.0.4 on 2024-04-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_360', '0018_alter_pbprojects_cost_estimate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbprojects',
            name='tat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
