# Generated by Django 5.0.4 on 2024-04-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_360', '0019_alter_pbprojects_tat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbprojects',
            name='allocated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='pbprojects',
            name='estimated_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pbprojects',
            name='priority_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pbprojects',
            name='requested_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
