NATIONALITIES = [
    ('', 'Select Nationality'),
    ('Afghan', 'Afghan'),
    ('Albanian', 'Albanian'),
    ('Algerian', 'Algerian'),
    ('American', 'American'),
    ('Andorran', 'Andorran'),
    ('Angolan', 'Angolan'),
    ('Anguillan', 'Anguillan'),
    ('Citizen of Antigua and Barbuda', 'Citizen of Antigua and Barbuda'),
    ('Argentine', 'Argentine'),
    ('Armenian', 'Armenian'),
    ('Australian', 'Australian'),
    ('Austrian', 'Austrian'),
    ('Azerbaijani', 'Azerbaijani'),
    ('Bahamian', 'Bahamian'),
    ('Bahraini', 'Bahraini'),
    ('Bangladeshi', 'Bangladeshi'),
    ('Barbadian', 'Barbadian'),
    ('Belarusian', 'Belarusian'),
    ('Belgian', 'Belgian'),
    ('Belizean', 'Belizean'),
    ('Beninese', 'Beninese'),
    ('Bermudian', 'Bermudian'),
    ('Bhutanese', 'Bhutanese'),
    ('Bolivian', 'Bolivian'),
    ('Citizen of Bosnia and Herzegovina', 'Citizen of Bosnia and Herzegovina'),
    ('Botswanan', 'Botswanan'),
    ('Brazilian', 'Brazilian'),
    ('British', 'British'),
    ('Virgin Islander', 'Virgin Islander'),
    ('Bruneian', 'Bruneian'),
    ('Bulgarian', 'Bulgarian'),
    ('Burkinan', 'Burkinan'),
    ('Burmese', 'Burmese'),
    ('Burundian', 'Burundian'),
    ('Cambodian', 'Cambodian'),
    ('Cameroonian', 'Cameroonian'),
    ('Canadian', 'Canadian'),
    ('Cape Verdean', 'Cape Verdean'),
    ('Cayman Islander', 'Cayman Islander'),
    ('Central African', 'Central African'),
    ('Chadian', 'Chadian'),
    ('Chilean', 'Chilean'),
    ('Chinese', 'Chinese'),
    ('Colombian', 'Colombian'),
    ('Comoran', 'Comoran'),
    ('Congolese (Congo)', 'Congolese (Congo)'),
    ('Congolese (DRC)', 'Congolese (DRC)'),
    ('Cook Islander', 'Cook Islander'),
    ('Costa Rican', 'Costa Rican'),
    ('Croatian', 'Croatian'),
    ('Cuban', 'Cuban'),
    ('Cymraes', 'Cymraes'),
    ('Cymro', 'Cymro'),
    ('Cypriot', 'Cypriot'),
    ('Czech', 'Czech'),
    ('Danish', 'Danish'),
    ('Djiboutian', 'Djiboutian'),
    ('Dominican', 'Dominican'),
    ('Citizen of the Dominican Republic', 'Citizen of the Dominican Republic'),
    ('Dutch East', 'Dutch East'),
    ('Timorese', 'Timorese'),
    ('Ecuadorean', 'Ecuadorean'),
    ('Egyptian', 'Egyptian'),
    ('Emirati', 'Emirati'),
    ('English', 'English'),
    ('Equatorial', 'Equatorial'),
    ('Guinean', 'Guinean'),
    ('Eritrean', 'Eritrean'),
    ('Estonian', 'Estonian'),
    ('Ethiopian', 'Ethiopian'),
    ('Faroese', 'Faroese'),
    ('Fijian', 'Fijian'),
    ('Filipino', 'Filipino'),
    ('Finnish', 'Finnish'),
    ('French', 'French'),
    ('Gabonese', 'Gabonese'),
    ('Gambian', 'Gambian'),
    ('Georgian', 'Georgian'),
    ('German', 'German'),
    ('Ghanaian', 'Ghanaian'),
    ('Gibraltarian', 'Gibraltarian'),
    ('Greek', 'Greek'),
    ('Greenlandic', 'Greenlandic'),
    ('Grenadian', 'Grenadian'),
    ('Guamanian', 'Guamanian'),
    ('Guatemalan', 'Guatemalan'),
    ('Citizen of Guinea-Bissau', 'Citizen of Guinea-Bissau'),
    ('Guinean', 'Guinean'),
    ('Guyanese', 'Guyanese'),
    ('Haitian', 'Haitian'),
    ('Honduran', 'Honduran'),
    ('Hong Konger', 'Hong Konger'),
    ('Hungarian', 'Hungarian'),
    ('Icelandic', 'Icelandic'),
    ('Indian', 'Indian'),
    ('Indonesian', 'Indonesian'),
    ('Iranian', 'Iranian'),
    ('Iraqi', 'Iraqi'),
    ('Irish', 'Irish'),
    ('Israeli', 'Israeli'),
    ('Italian', 'Italian'),
    ('Ivorian', 'Ivorian'),
    ('Jamaican', 'Jamaican'),
    ('Japanese', 'Japanese'),
    ('Jordanian', 'Jordanian'),
    ('Kazakh', 'Kazakh'),
    ('Kenyan', 'Kenyan'),
    ('Kittitian', 'Kittitian'),
    ('Citizen of Kiribati', 'Citizen of Kiribati'),
    ('Kosovan', 'Kosovan'),
    ('Kuwaiti', 'Kuwaiti'),
    ('Kyrgyz', 'Kyrgyz'),
    ('Lao Latvian', 'Lao Latvian'),
    ('Lebanese', 'Lebanese'),
    ('Liberian', 'Liberian'),
    ('Libyan', 'Libyan'),
    ('Liechtenstein citizen', 'Liechtenstein citizen'),
    ('Lithuanian', 'Lithuanian'),
    ('Luxembourger', 'Luxembourger'),
    ('Macanese', 'Macanese'),
    ('Macedonian', 'Macedonian'),
    ('Malagasy', 'Malagasy'),
    ('Malawian', 'Malawian'),
    ('Malaysian', 'Malaysian'),
    ('Maldivian', 'Maldivian'),
    ('Malian', 'Malian'),
    ('Maltese', 'Maltese'),
    ('Marshallese', 'Marshallese'),
    ('Martiniquais', 'Martiniquais'),
    ('Mauritanian', 'Mauritanian'),
    ('Mauritian', 'Mauritian'),
    ('Mexican', 'Mexican'),
    ('Micronesian', 'Micronesian'),
    ('Moldovan', 'Moldovan'),
    ('Monegasque', 'Monegasque'),
    ('Mongolian', 'Mongolian'),
    ('Montenegrin', 'Montenegrin'),
    ('Montserratian', 'Montserratian'),
    ('Moroccan', 'Moroccan'),
    ('Mosotho', 'Mosotho'),
    ('Mozambican', 'Mozambican'),
    ('Namibian', 'Namibian'),
    ('Nauruan', 'Nauruan'),
    ('Nepalese', 'Nepalese'),
    ('New Zealander', 'New Zealander'),
    ('Nicaraguan', 'Nicaraguan'),
    ('Nigerian', 'Nigerian'),
    ('Nigerien', 'Nigerien'),
    ('Niuean', 'Niuean'),
    ('North Korean', 'North Korean'),
    ('Northern Irish', 'Northern Irish'),
    ('Norwegian', 'Norwegian'),
    ('Omani', 'Omani'),
    ('Pakistani', 'Pakistani'),
    ('Palauan', 'Palauan'),
    ('Palestinian', 'Palestinian'),
    ('Panamanian', 'Panamanian'),
    ('Papua', 'Papua'),
    ('New Guinean', 'New Guinean'),
    ('Paraguayan', 'Paraguayan'),
    ('Peruvian', 'Peruvian'),
    ('Pitcairn Islander', 'Pitcairn Islander'),
    ('Polish', 'Polish'),
    ('Portuguese', 'Portuguese'),
    ('Prydeinig', 'Prydeinig'),
    ('Puerto Rican', 'Puerto Rican'),
    ('Qatari', 'Qatari'),
    ('Romanian', 'Romanian'),
    ('Russian', 'Russian'),
    ('Rwandan', 'Rwandan'),
    ('Salvadorean', 'Salvadorean'),
    ('Sammarinese', 'Sammarinese'),
    ('Samoan', 'Samoan'),
    ('Sao Tomean', 'Sao Tomean'),
    ('Saudi', 'Saudi'),
    ('Arabian', 'Arabian'),
    ('Scottish', 'Scottish'),
    ('Senegalese', 'Senegalese'),
    ('Serbian', 'Serbian'),
    ('Citizen of Seychelles', 'Citizen of Seychelles'),
    ('Sierra Leonean', 'Sierra Leonean'),
    ('Singaporean', 'Singaporean'),
    ('Slovak', 'Slovak'),
    ('Slovenian', 'Slovenian'),
    ('Solomon Islander', 'Solomon Islander'),
    ('Somali', 'Somali'),
    ('South African', 'South African'),
    ('South Korean', 'South Korean'),
    ('South Sudanese', 'South Sudanese'),
    ('Spanish', 'Spanish'),
    ('Sri Lankan', 'Sri Lankan'),
    ('St Helenian', 'St Helenian'),
    ('St Lucian', 'St Lucian'),
    ('Stateless', 'Stateless'),
    ('Sudanese', 'Sudanese'),
    ('Surinamese', 'Surinamese'),
    ('Swazi', 'Swazi'),
    ('Swedish', 'Swedish'),
    ('Swiss', 'Swiss'),
    ('Syrian', 'Syrian'),
    ('Taiwanese', 'Taiwanese'),
    ('Tajik', 'Tajik'),
    ('Tanzanian', 'Tanzanian'),
    ('Thai', 'Thai'),
    ('Togolese', 'Togolese'),
    ('Tongan', 'Tongan'),
    ('Trinidadian', 'Trinidadian'),
    ('Tristanian', 'Tristanian'),
    ('Tunisian', 'Tunisian'),
    ('Turkish', 'Turkish'),
    ('Turkmen', 'Turkmen'),
    ('Turks and Caicos Islander', 'Turks and Caicos Islander'),
    ('Tuvaluan', 'Tuvaluan'),
    ('Ugandan', 'Ugandan'),
    ('Ukrainian', 'Ukrainian'),
    ('Uruguayan', 'Uruguayan'),
    ('Uzbek', 'Uzbek'),
    ('Vatican citizen', 'Vatican citizen'),
    ('Citizen of Vanuatu', 'Citizen of Vanuatu'),
    ('Venezuelan', 'Venezuelan'),
    ('Vietnamese', 'Vietnamese'),
    ('Vincentian', 'Vincentian'),
    ('Wallisian', 'Wallisian'),
    ('Welsh', 'Welsh'),
    ('Yemeni', 'Yemeni'),
    ('Zambian', 'Zambian'),
    ('Zimbabwean', 'Zimbabwean'),
]

COMPLAINT_SUBTYPE_CHOICES = [
    (101, 'Cheque bounce related'),
    (102, 'Online Payment Related'),
    (103, 'Property Tax Website Related'),
    (201, '40% discount on the residential taxable value'),
    (202, 'Abhay Yojana'),
    (203, 'Address Correction'),
    (204, 'Assessment according to commencement'),
    (205, 'Assessment from Non residential(commercial) to residential'),
    (206, 'Assessment from residential to Non residential(commercial)'),
    (207, 'Assessment of Additional construction'),
    (208, 'Correction in ARV due to change in use of property'),
    (209, 'Correction in outstanding Property Tax'),
    (210, 'Correction of Name on Property tax bill'),
    (211, 'Correction of Property Area'),
    (212, 'Deletion of one name from two names on property tax bill'),
    (213, 'Finalizing of Property tax amount according to Court order and refunding the remaining'),
    (214, 'Nullifying Property tax bill regarding Double Bill / Reconstructive Property / Demolished Property'),
    (215, 'Other (Property Tax)'),
    (216, 'Property Tax bill not received'),
    (217, 'Receipt of Assessment Register'),
    (218, 'Recording of Assessment Register'),
    (219, 'Recording of Water tax according to residential & non residential in property tax'),
    (220, 'Removal of water tax due to installation of water meter'),
    (221, 'Self Assessment'),
    (222, 'Separation of Bill'),
    (223, 'Triple Tax Cancellation'),
    (301, 'Mobile Tower Related'),
    (401, 'Solar, Vermiculture, Rainwater harvesting discount'),
    (501, 'Correction in name according to official gazette'),
    (502, 'Property Tax NOC Related'),
    (503, 'Title Transfer'),
    (601, 'Contamination / Turbid Water Problem'),
    (602, 'Correction in water meter bill (Name/Address/Amount/ etc)'),
    (603, 'Leakage of Public Toilet'),
    (604, 'Low Pressure to Entire Area'),
    (605, 'Low water pressure to individual'),
    (606, 'Motor / Pump on water line of PMC'),
    (607, 'No water as per time table'),
    (608, 'No Water Supply'),
    (609, 'Others (Water Supply)'),
    (610, 'Pipeline/Valve Leakage of PMC line'),
    (611, 'Regarding code of conduct'),
    (612, 'Regarding ward limit'),
    (613, 'Removal / Installation of new water meters'),
    (614, 'Unauthorized tapping of water connection/Water Theft'),
    (615, 'Unauthorized use of water from Residential to Commercial area'),
    (616, 'Water Flowing / wastage'),
    (617, 'Water meter not working'),
    (618, 'Water misuse (washing Center/Spreading)'),
    (701, 'Others'),
    (702, 'Regarding Medical Bill'),
    (801, 'Applied for certified copy but no response'),
    (802, 'DP plan Demand'),
    (803, 'Flat addition and alteration'),
    (804, 'Number of flats in a building'),
    (805, 'Other'),
    (806, 'Plan submitted but not sanctioned'),
    (807, 'Regularisation of plots/constructions'),
    (808, 'Unauthorised alteration/renovation of building'),
    (809, 'Unauthorized construction/development'),
    (2001,	"Inaccurate Billing Amount"),
    (2002,	"Incorrect Billing Period"),
    (2003,	"Payment Deadline Missed"),
    (2004,	"Delayed Payment Notification"),
    (2005,	"Eligibility Criteria Misunderstood"),
    (2006,	"Exemption Application Rejected"),
    (2007,	"Contaminated Water Supply"),
    (2008,	"Water Odor and Taste Issues"),
    (2009,	"Prolonged Water Supply Interruption"),
    (2010,	"Sporadic Water Supply"),
    (2011,	"Low Pressure in Taps"),
    (2012,	"Weak Shower Flow"),
    (2013,	"Forced Eviction"),
    (2014,	"Land Occupation Dispute"),
    (2015,	"Poor Waste Management"),
    (2016,	"Lack of Sanitary Facilities"),
    (2017,	"Inadequate Road Infrastructure"),
    (2018,	"Limited Access to Basic Amenities"),
    (2019,	"Unauthorized Construction on Public Land"),
    (2020,	"Encroachment on Public Property"),
    (2021,	"Illegal Hawking"),
    (2022,	"Unregistered Street Vendors"),
    (2023,	"Unauthorized Parking in Restricted Zones"),
    (2024,	"Occupying No Parking Areas"),
    (2025,	"Permit Processing Delay"),
    (2026,	"Documentation Incompletion"),
    (2027,	"Non-compliance with Building Regulations"),
    (2028,	"Use of Unauthorized Building Materials"),
    (2029,	"Unapproved Construction Materials"),
    (2030,	"Inappropriate Material Usage"),
    (2031,	"Poor Sanitary Conditions"),
    (2032,	"Inadequate Waste Disposal Facilities"),
    (2033,	"Improper Medical Waste Handling"),
    (2034,	"Disregard for Biohazard Disposal Protocol"),
    (2035,	"Improper Disposal of Expired Medications"),
    (2036,	"Inadequate Medical Waste Disposal Methods"),
]

COMPLAINT_TYPE_CHOICES = [
    (1, 'Property Tax-Computer Section'),
    (2, 'Property TaxAssessment/Payment'),
    (3, 'Property Tax-Mobile tower'),
    (4, 'Property Tax-Solar & Rainwater'),
    (5, 'Property Tax-TAT (Title Transfer)'),
    (6, 'Water Supply'),
    (7, 'Urban Poor Scheme'),
    (8, 'Building Permission'),
    (9,	"Incorrect Billing"),
    (10, "Late Payment Charges"),
    (11, "Exemptions Not Applied"),
    (12, "Water Quality"),
    (13, "Water Supply Disruption"),
    (14, "Low Water Pressure"),
    (15, "Illegal Settlements"),
    (16, "Sanitation Issue"),
    (17, "Lack of Infrastructure"),
    (18, "Public Land Encroachment"),
    (19, "Unauthorized Vendors"),
    (20, "Illegal Parking"),
    (21, "Delay in Permit Issuance"),
    (22, "Illegal Construction"),
    (23, "Unapproved Building Materials"),
    (24, "Unhygienic Conditions"),
    (25, "Hospital Waste Management"),
    (26, "Improper Disposal of Medical Waste"),
]